variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
    SolutionBaseName: 'DFC.Api.AppRegistry'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v2.0.1
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
    - job: TestArmTemplates
      displayName: "Test & package ARM template(s)"
      steps:
      - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
        parameters:
          ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
          SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - job: PublishApimPolicy
      displayName: Publish Apim Policy
      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Apim Policy
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/Resources/ApimPolicy"
          artifactName: DFC.Api.AppRegistry.Resources.ApimPolicies

    - job: BuildDotNetCore
      displayName: Build-DotNetCore
      steps:
      - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
        parameters:
         SolutionBaseName: $(SolutionBaseName)
         BuildPlatform: $(BuildPlatform)
         BuildConfiguration: $(BuildConfiguration)
         PublishWebApp: true
         TestSuffix: UnitTests
